version: '3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: rhcontrol
    ports:
      - "3307:3306"
    networks:
      - rh-control
      
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - rh-control
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    links:
      - zookeeper
    depends_on:
      - zookeeper
    networks:
      - rh-control
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    links:
      - kafka
    depends_on:
      - kafka
    networks:
      - rh-control
    ports:
      - "19000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:29092
      
  rhcontrolmail:
    image: dyegohbb/rhcontrolmail:1.0.0
    links:
      - kafka
    ports:
      - "8082:8082"
    networks:
      - rh-control
    environment:
      KAFKA_HOST: kafka:29092
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092

  rhcontrol:
    image: dyegohbb/rhcontrol-2:1.0.0
    depends_on:
      - db
      - kafka
    links:
      - db
      - kafka
    ports:
      - "8000:8000"
    networks:
      - rh-control
    environment:
      KAFKA_HOST: kafka:29092
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: rhcontrol
      
networks:
  rh-control:
    driver: bridge

